spring:

    application:
        name: taskPlanner

    profiles:
        active: dev

    data:
        jpa.repositories.enabled: true

    h2:
        console:
            enabled: true
            settings:
               trace: false
               web-allow-others: false

logging:
    file: app.log
    level:
        root: INFO
        org.springframework.web: INFO
        com.gralll.taskplanner: INFO
        hibernate: INFO